name: iOS Build (Flutter)

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      build_mode:
        description: 'Build mode: release or debug'
        required: true
        default: 'release'

jobs:
  build-ios:
    runs-on: macos-14
    env:
      FLUTTER_VERSION: 'stable'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: stable

      - name: Flutter doctor
        run: flutter doctor -v

      - name: Fetch dependencies
        run: flutter pub get

      - name: Create iOS and other platforms if missing
        run: |
          if [ ! -d ios ]; then flutter create .; fi

      - name: Build iOS (unsigned .app)
        env:
          CI: true
        run: |
          BUILD_MODE="${{ github.event.inputs.build_mode }}"
          if [ -z "$BUILD_MODE" ]; then BUILD_MODE=release; fi
          echo "Using build mode: $BUILD_MODE"
          flutter build ios --no-codesign --$BUILD_MODE

      - name: List build outputs
        run: |
          echo "Listing build outputs:"
          ls -R build/ios || true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ios-build
          path: |
            build/ios/iphoneos/*.app
            build/ios/archive/*.xcarchive
          if-no-files-found: warn

